[markup]
	ignoreLogs = ['warning-goldmark-raw-html']
[markup.goldmark.renderer]
	unsafe = true
baseURL = "https://nonlinear.nyc/version5/"
languageCode = "en-us"
title = "Nonlinear — version5"
publishDir = "docs"

[params]
author = "Nicholas Frota"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]

[mediaTypes."application/rss+xml"]
suffixes = ["xml"]

[outputFormats.RSS]
mediaType = "application/rss+xml"
baseName = "index"
isPlainText = true
